title: zhonghaoyuan's Homepage
page-top-title: zhonghaoyuan
top-section-bg-text: digital-chip-designer
home-subtitle: zhonghaoyuan | 钟浩源
copyright-text: '&copy; zhonghaoyuan 2023-2026. All Rights Reserved.'
